### PR TITLE
Fix end address for paged area

### PR DESCRIPTION
**Pull request by EgorKin**

### CODE REVIEW

**Review by podonoghue — COMMENTED** [review]
It is a while since I wrote this code so I may be misunderstanding what I did then but...
I believe the existing code is correct.
It is looking for a block that crosses into the paged area (i.e. starts before and ends within/after) and truncating to the start of the region.  The paged area will be picked up in the next iteration.

the comment is wrong. It should be:
// Stop before paged area

**Comment by EgorKin** [comment]
Of course I may be wrong but I suppose that this part of code check condition: block start at paged area but block end after paged area and fix end address to end of paged area (0xBFFF).

IMO "It is looking for a block that crosses into the paged area (i.e. starts before and ends within/after" - it is all about first "if" condition at line 283. And comment "Stop before paged area" mean that end = 0x7FFF.

Based on datasheet for MC9S12XEP100:
mc9s12xep100

This how I read this code:

// Check if block started at first unpaged 16K FLASH but end outside
`if ((start<0x8000) && (pagedEnd>=0x8000))
{
// Stop at end of unpaged area
end = 0x7FFF;
}`

// Check if block started at paged 16K FLASH window but end outside
`if ((pagedStart<0xC000) && (pagedEnd>=0xC000)) {
               // Stop at end of paged area
               end = 0xBFFF;
            }`
// No need to check second unpaged area because it end at 0xFFFF

// If block at paged area then set PPAGE reg
`if ((pagedStart>=0x8000) && (pagedEnd<0xC000)) {
               // Within paged area
               rc = bdmInterface->writeMemory(1, 1, currentPPageAddress, &page);
               if (rc != BDM_RC_OK) {
                  return rc;
               }
            }`

**Comment by podonoghue** [comment]
You are quite right - I just can't use Github online properly.
I was looking at the merged file.

bye

**Comment by EgorKin** [comment]
I look at this part of code more deeper and have feeling that it`s need some modifications anyway.

Lets debug this code with next conditions:
`start = 0xC0B003;
end = 0xC0C001;`

`while(start <= end)` true
`size = end-start+1;` size=0xFFF
`size>(long)sizeof(data)` false
`isPaged` true
`page = 0xC0`
`pageStart = 0xB003`
`pageEnd = pageStart+size-1` pageEnd=0xC001
//check
`if ((start<0x8000) && (pagedEnd>=0x8000))` false
`if ((pagedStart<0xC000) && (pagedEnd>=0xC000))` true => `end = 0xBFFF;`
`if ((pagedStart>=0x8000) && (pagedEnd<0xC000))` false
and we goto
`else {
    // Non-paged area - validate address
    if (page != 0) {
        writeStatus("Non-paged area with non-zero page number (entry #%d), [0x%06lX, 0x%06lX]\n", row+1, start, end);
        return BDM_RC_ILLEGAL_PARAMS;
    }
}`

but end variable already fixed to 0xBFFF value and this message unrelevant. And we don`t read anything. If ignore my last pull request, message still unrelevant because end var. changed to 0xC000 and differ from user input value too.

But if we fixed not "end" var. but "pageEnd" var. then:
`if ((pagedStart<0xC000) && (pagedEnd>=0xC000))` true => pageEnd = 0xBFFF;
`if ((pagedStart>=0x8000) && (pagedEnd<0xC000))` true
`rc = bdmInterface->writeMemory(1, 1, currentPPageAddress, &page);`
`size = pagedEnd-pagedStart+1;` size=0xFFD
`rc = bdmInterface->readMemory(width, size, pagedStart, data);`
`start += size;` start=0xC0C000

and we go to next while() iteration

`while(start <= end)` true because start=end
`size = end-start+1;` size=1
`size>(long)sizeof(data)` false
`isPaged` true
`page = 0xC0`
`pageStart = 0xC000`
`pageEnd = pageStart+size-1` pageEnd=0xC000
//check
`if ((start<0x8000) && (pagedEnd>=0x8000))` false
`if ((pagedStart<0xC000) && (pagedEnd>=0xC000))` false
`if ((pagedStart>=0x8000) && (pagedEnd<0xC000))` false
and we goto
`else {
    // Non-paged area - validate address
    if (page != 0) {
        writeStatus("Non-paged area with non-zero page number (entry #%d), [0x%06lX, 0x%06lX]\n", row+1, start, end);
        return BDM_RC_ILLEGAL_PARAMS;
    }
}`

start and end vars are correct now and we already read corrected amount of bytes.

IMHO weak point is that you fixed end variable but did not use it at current while() iteration.

It`s not pull request nor issue but just for you know about.
P.S. Used "in my brain debugger" so I can loose something important :)

**Pull request merged**
